### ISSUE TITLE
New Kirki update

### ISSUE THREAD

**Issue by ComicCrusaders** [aristath/_s#9]
After the new update my site has gone crazy! Cant even customize anymore! Where can i dL the prior release so all goes back to normal?

**Comment by aristath** [comment]
> After the new update my site has gone crazy! Cant even customize anymore!

What do you mean exactly? 
What theme are you using? 
Is it up to date? 
Do you get any errors in the console?

> Where can i dL the prior release so all goes back to normal?

You can find all releases on https://github.com/aristath/kirki/releases and also on the bottom of https://wordpress.org/plugins/kirki/advanced/

I'm guessing you'll want to use 2.3.8 since that's the previous stable version before today's version.

But please provide as many details as possible about the actual issue so that we may fix it.
Kirki issues should be submitted on https://github.com/aristath/kirki/issues
